// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/user","layout":false,"id":"1"},"2":{"icon":"smile","name":"登录","path":"/user/login","parentId":"1","id":"2"},"3":{"parentId":"1","id":"3"},"4":{"path":"/welcome","name":"欢迎","icon":"smile","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"封面管理","icon":"picture","path":"/cover","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"作者管理","icon":"user","path":"/creators","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"分类管理","icon":"group","path":"/depts","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"作品管理","icon":"solution","path":"/works","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"9"},"10":{"parentId":"ant-design-pro-layout","id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Welcome__index" */'@/pages/Welcome/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__CoverManage__index" */'@/pages/CoverManage/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__CreatorList__index" */'@/pages/CreatorList/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__DeptList__index" */'@/pages/DeptList/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__WorkList__index" */'@/pages/WorkList/index.tsx')),
'9': React.lazy(() => import( './EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
