// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import PictureOutlined from '/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/node_modules/@ant-design/icons/es/icons/PictureOutlined';
import UserOutlined from '/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/node_modules/@ant-design/icons/es/icons/UserOutlined';
import GroupOutlined from '/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/node_modules/@ant-design/icons/es/icons/GroupOutlined';
import SolutionOutlined from '/Users/karl.huangboehringer-ingelheim.com/Documents/project/skd-gallery-admin/node_modules/@ant-design/icons/es/icons/SolutionOutlined';
export default { SmileOutlined, PictureOutlined, UserOutlined, GroupOutlined, SolutionOutlined };
